env: "dev"
grpc_clients:
  auth_service_address: "localhost:60000"
  user_service_address: "localhost:60001"
  matcher_service_address: "localhost:60002"
  file_storage_service_address: "localhost:60005"
  chat_service_address: "localhost:60005"
http_server:
  address: ":8082"
  timeout: 10s
  idle_timeout: 10s
cors:
  allowed_origins:
    - "http://localhost:8888"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "HEAD"
  allowed_headers:
    - "Content-Type"
    - "Authorization"
    - "X-Requested-With"
  allow_credentials: true
